kubermatic/kubecarrier

hack/krew-manifest/main.go

As part of the release process, we generated windows download URL with wrong filename extension (`.tar.gz` instead of `.zip`)  This fixes it. 
```release-note
NONE
```

Fixed krew manifest URL for windows

---

docs/api_reference.md
hack/docgen.sh

Due to docs folder structure reorganization, the `make generate` command is broken. This fixes it. 
```release-note
NONE
```

Fixed make generate

---

test/scenarios/simple.go

Due to prow's cluster slowness, sometimes e2e test are failing on timeout for the CatalogEntrySet operations. This PR increased the timeout to 1 minute from default 30s. 
e.g. https://github.com/kubermatic/kubecarrier/pull/287#issuecomment-598676830
```release-note
NONE
```

Incresed catalogentrySet timeout in Scenarios/simple e2e test

---

pkg/internal/util/object.go

Deletion error isn't propagated up the call chain. This PR fixes it.
```release-note
NONE
```

propagate deletion error upwards

---

hack/gen-tasks.go
pkg/cli/internal/cmd/delete/account.go
pkg/cli/internal/cmd/delete/delete.go
pkg/cli/internal/cmd/root.go
pkg/testutil/framework.go
test/integration/cli.go
test/integration/integration.go
test/integration/servicecluster.go
test/scenarios/simple.go

This PR adds account deletion helper to the kubecarrier CLI. What's special about is the `--force` flag which basically nukes the account --> cleaning up all deletion blocking objects and destroying the whole account.
```release-note
* added `kubecarrier delete account` CLI helper 
```

Added account deletion helper

---

Makefile

Upgrade the cert-manager to v0.14.0
Release note: https://cert-manager.io/docs/release-notes/release-notes-0.14
Fixes #
```release-note
NONE
```

Upgrade the cert-manager to v0.14.0

---

hack/krew-manifest/main.go

This PR aims to address concerns in the https://github.com/kubernetes-sigs/krew-index/pull/540 regarding including kubecarrier kubectl plugin into official krew index.
```release-note
NONE
```

Updated krew manifest information

---

pkg/manager/internal/webhooks/customresourcediscovery_webhook.go
pkg/manager/internal/webhooks/derivedcustomresource_webhook.go
test/integration/derivedcr.go
test/integration/servicecluster.go

This PR disabled CustromResourceDiscovery/DerivedCustromResource deletion webhooks due to their buggy behavior.
```release-note
* disabled CustromResourceDiscovery/DerivedCustromResource deletion webhooks
```

disabling CustromResourceDiscovery/DerivedCustromResource deletion webhooks

---

pkg/internal/resources/catapult/catapult.go
pkg/internal/resources/catapult/catapult.golden.yaml
pkg/internal/resources/elevator/elevator.go
pkg/internal/resources/elevator/elevator.golden.yaml
pkg/manager/internal/webhooks/customresourcediscovery_webhook.go
pkg/manager/internal/webhooks/derivedcustomresource_webhook.go
test/integration/servicecluster.go

CatalogEntrySet, in the end, creates same-named Elevator & Catapult instances, which create the same-named & conflicting cluster roles for manager's view permissions & webhooks. 
This fixes the issue
```release-note
* reenabled CustromResourceDefinition/DerivedCustomResource webhooks
```

Fix conflicting cluster role names for same named catapult & elevator

---

test/integration/derivedcr.go

Since the #336 was merged to the master, this PR enables the deletion webhook test for DerivedCustomResource
Fixes #
```release-note
NONE
```

Enable deletion webhook test for DerivedCustomResource

---

Makefile

Kind version 0.8.x broke our usual setup pipeline due to: 
https://github.com/kubernetes-sigs/kind/pull/1583
This fixes it in backward compatible fashion. 
```release-note
NONE
```

kind 0.8.x workaround

---

pkg/apiserver/internal/v1/offering.go

This PR fixes the bug that running `watcher.Stop()` on a nil watcher if the creation of the watcher returns non-nil error.
Fixes #
```release-note
NONE
```

Fix watcher.Stop() on a nil watcher

---

pkg/apiserver/apiserver.go

when using the JSON REST API calls to our API server it skips the gRPC server middlewares handling auth & other goodies. This PR fixes it 
```release-note
NONE
```

fixed JSON REST API calls skipping gRPC middlewares

---

test/integration/apiserver.go

This is attempt into making watch e2e test more stable
```release-note
NONE
```

Watch test refactor

---

pkg/catapult/internal/controllers/adoption_controller.go
pkg/catapult/internal/controllers/adoption_controller_test.go
pkg/elevator/internal/controllers/adoption_controller.go
pkg/elevator/internal/controllers/adoption_controller_test.go
pkg/testutil/mockclient/client.go

There is a race condition, when adopted objects are deleted, which will re-create the object and prevent deletion.
This PR should fix that bug.
It also introduces a Mock of the kubernetes client, as it's way easier to assert something was NOT called this way.
Also it finally uses that mock instead of fakeclient for new tests.
Fixes #
```release-note
NONE
```

Fix crd instance cleanup

---

pkg/apiserver/apiserver.go

It removes rendundant logging. Due to gRPC logging middleware, it shall handle the proper request logging, together with the returned status code. 
```release-note
NONE
```

Removed unnecessary logging

---

.prow.yaml

All prow validation jobs are kept in the infra repository, because this makes Prow updates much easier. It also makes it so that the prow validation is always mandatory and run before anything else from the in-repo config is even looked at. That is a nice security feature we want to keep, hence this PR moves the job into the infra repo.
```release-note
NONE
```

move validate-prow-yaml job to infra repo

---

pkg/manager/internal/controllers/catalogentryset_controller.go
pkg/manager/internal/controllers/customresourcediscoveryset_controller.go
pkg/manager/internal/controllers/customresourcediscoveryset_controller_test.go

This PR fixed the customResourceDiscoverySet Bug. The bug is as follows:
* 2 provides use the same-named `CustomResourceDiscoverySet`
* The `	// Cleanup uncontrolled CRDiscoveries` which was intended to clean up CRDiscoveries for deleted service clusters assassinates other providers `CRDiscoveries`. Why? Because the lookup isn't namespace bound but crosses the namespace boundary. 
This PR fixes this in 2 ways, for extra safety:
* the lookup is now namespace bound
* the label value is now namespace aware
```release-note
NONE
```

Fix customResourceDiscoverySet controller

---

pkg/internal/resources/apiserver/apiserver.go
pkg/internal/resources/catapult/catapult.go
pkg/internal/resources/catapult/catapult.golden.yaml
pkg/internal/resources/constants/labels.go
pkg/internal/resources/elevator/elevator.go
pkg/internal/resources/elevator/elevator.golden.yaml
pkg/internal/resources/ferry/ferry.go
pkg/internal/resources/manager/manager.go

When registering multiple CRDs in the same namespace the webhook selector will mach all elevator/catapult instances, do round robin load balancing and lead to this error:
```
Error from server (InternalError): error when creating "./master_cluster/kubecarrier/services/cert-svc1-tenant1.yaml": Internal error occurred: failed calling webhook "mcertificate.kubecarrier.io": Post https://certificates-svc-1-catapult-webhook-service.provider-1.svc:443/mutate-svc-1-provider-1-v1alpha2-certificate?timeout=30s: x509: certificate is valid for certificates-svc-2-catapult-webhook-service.provider-1.svc, certificates-svc-2-catapult-webhook-service.provider-1.svc.cluster.local, not certificates-svc-1-catapult-webhook-service.provider-1.svc
```
**Which issue(s) …

Add common labels to service selector, to avoid service endpoint overlap

---

Makefile
docs/api_reference/_index.md

Sometimes our api-reference is outdated, this PR adds `make docs` in `make generate` so our lint can against that.
Fixes #
```release-note
NONE
```

Enable make docs in make generate

---

Makefile

The current implementations of mounts on Linux provide a consistent view of a host directory tree inside a container: reads and writes performed either on the host or in the container are immediately reflected in the other environment, and file system events (inotify, FSEvents) are consistently propagated in both directions.
On Linux, these guarantees carry no overhead, since the underlying VFS is shared directly between host and container. However, on macOS (and other non-Linux platforms) there are significant overheads to guaranteeing perfect consistency.
This PR using `delegated` (the container’s view is authoritative (permit delays before updates on the container appear in the host)) to increase the performance of `make generate` on MacOS.
Ref: …

Increase make generate performance on Mac by using delegated mount mode

---

pkg/catapult/internal/controllers/managementclusterobj_controller.go

don't try to update management cluster object status if it does not exist in the service cluster object
Fixes #549 
```release-note
NONE
```

check if status exists in management cluster object
