pkg/manager/internal/controllers/catalogentryset_controller.go, pkg/manager/internal/controllers/catalogentryset_controller_test.go, test/integration/servicecluster.go
Fixes #
```release-note
NONE
```
=> [Bug-Fix]Pass the WebhookStrategy from CatalogEntrySet to CustomResourceDiscoverySet

.github/ISSUE_TEMPLATE/feature_request.md
Remove the default assignee in the feature_request.md, so everytime people create issuses, they will not be assigned to @thetechnick 
Fixes #
```release-note
NONE
```
=> Remove the default assignee in the feature_request.md

Makefile, config/dockerfiles/test.Dockerfile, hack/validate-directory-clean.sh
This PR adds `make generate` to CI/CD.
Fixes #286 
```release-note
NONE
```
=> Add make generate to CI/CD

config/dockerfiles/test.Dockerfile
Fixes #
```release-note
NONE
```
=> Upgrade golangci-lint to v1.24.0

Makefile, cmd/tower/main.go, config/dockerfiles/tower.Dockerfile, hack/gen-tasks.go, pkg/tower/tower.go
Fixes #327 
```release-note
NONE
```
=> Bootstrap tower

README.md
We have upgraded cert-manager to v0.14.0 a few days ago, but we are still using v0.13.0 in the README.md, this PR updates the README.md to use cert-manager v0.14.0 also.
Fixes #
```release-note
NONE
```
=> [README.md update] Update cert-manger to v0.14.0

pkg/fakeoperator/internal/controllers/db_controller.go
Fixes #
```release-note
NONE
```
=> Add an empty line between kubebuilder markers and function to make the rbac auto-generated

.prow.yaml, pkg/internal/util/clientwatcher.go, pkg/testutil/framework.go, test/integration/derivedcr.go, test/integration/servicecluster.go
Fixes #290 
```release-note
NONE
```
=> Increase CI/CD resources

hack/boilerplate/boilerplate.proto.txt
This PR adds a boilerplate file for *proto files to validate headers.
Fixes #
```release-note
NONE
```
=> Add boilerplate file for *.proto files

pkg/apiserver/apiserver.go
Enforces TLS for the API server.
This is needed, because without TLS HTTP2 is not supported by the golang http server.
Fixes #
```release-note
NONE
```
=> Enforce TLS for API Server

pkg/apiserver/internal/v1/offering.go
Fixes #
```release-note
NONE
```
=> Fix two typos in offering service

.prow.yaml, Makefile, config/dockerfiles/dev.Dockerfile
`github.com/stretchr/testify` downloaded on each `make generate` run, so I've added it to dev image
Fixes #
```release-note
NONE
```
=> Update dev image

pkg/apis/fake/v1/db_types.go, pkg/fakeoperator/internal/webhooks/db_webhook_test.go
Fixes #
```release-note
NONE
```
=> fix e2e operator default config params

pkg/internal/reconcile/admissionregistration.go, pkg/internal/reconcile/certmanager.go
Fixes #429 
```release-note
NONE
```
=> Disable debugging log of CLI

Makefile, docs/_index.md, docs/api_reference/_index.md, docs/architecture/_index.md, docs/getting_started/10_requirements.md, docs/getting_started/20_installation.md, docs/getting_started/30_accounts.md, docs/getting_started/40_clusters.md, docs/getting_started/50_catalogs.md, docs/getting_started/60_crds.md, docs/getting_started/_index.md, docs/glossary/_index.md, docs/repository_organization/_index.md, hack/docgen.sh, hack/validate-directory-clean.sh
Updates the /docs folder to be up-to-date with docs.loodse.com.
Fixes #
```release-note
NONE
```
=> Bring docs up-to-date with docs.loodse.com

docs/manifests/accounts.yaml, pkg/manager/internal/webhooks/account_webhook.go
Fixes #
```release-note
NONE
```
=> add account missing metadata

pkg/internal/util/cmd.go
Debugging logs have been disabled for master branch, but some changes are introduced by #398 , this PR disable debug logs for feature-api-server branch.
Fixes #
```release-note
NONE
```
=> Disable debug log for CLI

pkg/apiserver/internal/v1/instance.go
Fixes #448 
```release-note
NONE
```
=> add validation for instance create/delete req

.prow.yaml, config/dockerfiles/test.Dockerfile
This PR adds a simple init-system to our test container, that can reap zombies and will actually proxy signals to it's child process, which will hopefully help our test stability.
Fixes #
```release-note
NONE
```
=> Add init-system to test container

.prow.yaml, Makefile, config/dockerfiles/dev.Dockerfile
Fixes #
```release-note
NONE
```
=> Install go-init in dev image

Makefile
=> kind cluster sync creation

pkg/apiserver/internal/authorizer/authorizer.go
ref: #473 
```release-note
NONE
```
=> Remove SubjectAccessReview from error message

hack/.e2e-test.sh, hack/audit.yaml, hack/testjsonformat/main.go, pkg/apiserver/internal/auth/htpasswd/htpasswd.go, pkg/apiserver/internal/authorizer/authorizer.go, pkg/cli/internal/cmd/sut/service.go, pkg/cli/internal/cmd/sut/sut.go, pkg/internal/reconcile/rbac.go, test/integration/apiserver.go
Further product stability improvements:
* minor fixes here and there
* fixed update storm where ClusterRole update ping-pong with kubecarrier-operator and aggregation controller
```release-note
NONE
````
=> Further product stability improvements

pkg/apiserver/api/v1/auth.go, pkg/apiserver/authorizer/authorizer.go, pkg/apiserver/internal/authorizer/authorizer.go
add checkers `_ authorizer.AuthRequest = (*ListRequest)(nil)`
to make sure that requests implements `AuthRequest` interface correctly.
Also moved out constants that we are using in `apiserver/v1` from the `internal` package.
Fixes #
```release-note
NONE
```
=> Ensure that AuthRequest implemented

pkg/apiserver/internal/v1/instance.go, pkg/apiserver/internal/v1/offering.go, pkg/apiserver/internal/v1/util.go
Fixes #
```release-note
NONE
```
=> add util watch method

.prow.yaml, pkg/catapult/internal/controllers/adoption_controller_test.go, pkg/catapult/internal/controllers/managementclusterobj_controller.go, pkg/elevator/internal/controllers/adoption_controller_test.go, pkg/ferry/internal/controllers/customresourcediscovery_controller.go, pkg/ferry/internal/controllers/serviceclusterassignment_controller.go, pkg/internal/owner/owner.go, pkg/internal/owner/owner_test.go, pkg/internal/owner/reconcile.go, pkg/internal/owner/reconcile_test.go, pkg/manager/internal/controllers/account_controller.go, pkg/manager/internal/controllers/catalog_controller_test.go, pkg/manager/internal/controllers/customresourcediscovery_controller.go, pkg/manager/internal/controllers/customresourcediscovery_controller_test.go, pkg/manager/internal/controllers/derivedcustomresource_controller.go, pkg/manager/internal/controllers/derivedcustomresource_controller_test.go, pkg/operator/internal/controllers/util.go, test/integration/account.go, test/integration/apiserver.go, test/integration/catalog.go, test/integration/derivedcr.go, test/integration/fakedb.go, test/integration/integration.go, test/integration/servicecluster.go, test/scenarios/scenarios.go
Fixes #487 
```release-note
NONE
```
=> Single owner override

.goreleaser.yaml
Fixes #
```release-note
NONE
```
=> Fix apiserver build for go-releaser

config/dockerfiles/test.Dockerfile
It's missing in #500 
```release-note
NONE
```
=> added boilerplate binary to test.Dockerfile

Makefile, config/dockerfiles/dev.Dockerfile
=> Added boilerplate to dev image

.prow.yaml
Fixes #
```release-note
NONE
```
=> Update prow configuration to use the v6 dev image

Makefile
This PR replaces sudo chown with --user flag in docker.
Fixes #
```release-note
NONE
```
=> Replace sudo chown with --user flag in docker

hack/verify-boilerplate.sh
This can make debug easier because you can see exactly which header is wrong.
Fixes #
```release-note
NONE
```
=> Enable verbose for boilerplate

pkg/catapult/internal/controllers/adoption_controller.go, pkg/catapult/internal/controllers/managementclusterobj_controller.go, pkg/ferry/internal/controllers/customresourcediscovery_controller.go, pkg/ferry/internal/controllers/serviceclusterassignment_controller.go
ref: https://github.com/kubernetes-sigs/controller-runtime/blob/ca25c1f1014d6db6eba745e04f180d272a854e9a/pkg/source/source.go#L67-L72
Fixes #
```release-note
NONE
```
=> Use NewKindWithCache

README.md
Fixes #
```release-note
NONE
```
=> Add roadmap to readme

pkg/manager/internal/controllers/account_controller.go
Since Account is cluster-scoped object, we can use `controllerutil.SetOwnerReference` and offload garbage collection to Kubernetes.
Fixes #349 
```release-note
NONE
```
=> Use Ower handling from controller-runtime for Account 

pkg/apis/operator/v1alpha1/catapult_types.go, pkg/apis/operator/v1alpha1/elevator_types.go, pkg/apis/operator/v1alpha1/ferry_types.go, pkg/apis/operator/v1alpha1/kubecarrier_types.go, test/integration/derivedcr.go, test/integration/servicecluster.go
Fixes #541 Fixes #539 
```release-note
Fix Paused flag bugs.
```
=> Fix paused flag bugs

OWNERS_ALIASES
Fixes #
```release-note
NONE
```
=> Add Rastislav as owner

OWNERS_ALIASES
Fixes #
```release-note
NONE
```
=> Remove jiachengxu from OWNERS
